### ISSUE TITLE
When text is generated, I change the window or add a new chat. The program will be crashed and broken

### ISSUE THREAD

**Issue by PinkR1ver** [nanbingxyz/5ire#8] opened 2024-11-22 06:27 UTC
As the title says.

**Comment by nanbingxyz** [comment] 2024-11-22 06:47
@PinkR1ver Windows or Mac ? And which version?

**Comment by PinkR1ver** [comment] 2024-11-22 07:10
OS: Windows 11
5ire version: 0.8.1

**Comment by nanbingxyz** [comment] 2024-11-22 12:20
@PinkR1ver Unable to reproduce the issue. Does the app crash when you start a new chat during generation, or after generation is complete? And what model are you using?

**Comment by nanbingxyz** [comment] 2024-11-26 15:01
@PinkR1ver Still unable to reproduce it. However,I have fixed issue #9 on v0.8.2. I'll close this and recreate it if it happens again.

**Closed by nanbingxyz** 2024-11-26 15:01 UTC
